django_project_to_drf/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup_view, name='signup'),
    path('login/', views.login_view, name = 'login'),
    path('logout/', views.logout_view, name = 'logout'),
    path('profile/<str:username>/', views.profile_view, name='profile'),
    path('profile/<str:username>/edit', views.profile_edit, name='profile_edit'),
    path('follow/<str:username>', views.follow_view, name='follow'),
]

django_project_to_drf/products/urls.py
from django.urls import path
from . import views

app_name = 'products'

urlpatterns = [
    path('', views.product_list_view, name='product_list'),
    path('create/', views.product_create_view, name='product_create'),
    path('<int:pk>/', views.product_detail_view, name='product_detail'),
    path('<int:pk>/update/', views.product_update_view, name='product_update'),
    path('<int:pk>/delete/', views.product_delete_view, name='product_delete'),
    path('<int:pk>/like/', views.product_like_view, name='product_like'),
]

django_project_to_drf/spartamarket/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('products/', include('products.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django_project_to_drf/products/models.py
from django.db import models
from django.conf import settings
import re
from django.core.exceptions import ValidationError 

# 상품 이미지를 저장할 경로를 생성하는 함수
def product_image_path(instance, filename):
    return f'product_images/{instance.user.username}/{filename}'

# 파이썬의 정규표현식
#해시태그가 유효한지 검사하는 사용자 정의 함수를 선언. (해시태그는 띄어쓰기 특수문자를 허용하지 않는다.)
def validation_hashtag(value):
    if not re.match(r'^[0-9a-zA-Z_]+$', value): # 정규표현식 => 공백 / 특수문자를 불허하는 코드.
        raise ValidationError('해시태그는 알파벳, 숫자, 언더스코어만 가능합니다!')

# 해시태그를 저장하는 모델.
class HashTag(models.Model):
    name = models.CharField(max_length=50, unique=True, validators=[validation_hashtag])
    
    def __str__(self):
        return f'#{self.name}'

# 사용자의 등록한 상품을 저장하는 모델
class Product(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='products')
    title = models.CharField(max_length=100)
    description = models.TextField()
    image = models.ImageField(upload_to=product_image_path, blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    
    #user like(좋아요)는 ManytoManyField 다대다 관계를 설정 가능.(user 모델과)
    # 상품에 좋아요가 없을 수도 있기 때문에, blank=True 
    likes = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='liked_products', blank=True)
    # 상품과 연결 돼 있는 해시태그 = 다대다 관계
    hashtags = models.ManyToManyField(HashTag, related_name='products', blank=True)
    views = models.PositiveIntegerField(default=0)
    
    def like_count(self):
        return self.likes.count()
    
    def __str__(self):
        return self.title

django_project_to_drf/products/forms.py
from django import forms
from .models import Product, HashTag

class ProductForm(forms.ModelForm):
    hashtags_str = forms.CharField(required=False)
    
    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user', None)  # user 인자를 뽑는 것
        super().__init__(*args, **kwargs)  # 부모 클래스 초기화
    
    class Meta:
        model = Product
        fields = ['title', 'description', 'image', 'hashtags_str']
    # save 메서드는 폼에서 입려간 데이터를 db에 적재한다.   
    def save(self, commit=True):
        # 부모 클래스의 save 매서드를 호출하되, commit=False 할 것이다 -> 해당 상품을 들고도오되 db에는 product 저장하지 않겠다.
        # 1. product 객체를 생성하고, 추가 작업(해시태그 처리)을 완료한뒤에서 commit을 한다(db에 반영한다.)
        # 2. user와 연결을 또 시켜줘야합니다. 그 결과를 db에 적재하기 위해서 일단 commit을 false로 둔다.
        product = super().save(commit=False)
        if self.user:
            product.user = self.user
        
        if commit:
            product.save()
        
        # 해시태그 처리
        # 입력받은 hashtag_str 문자열을 쉼표나 공백으로 구분해볼게요! (제한)
        # 각 해시태그를 db에 저장하거나, 이미 존재하면 가져올거임
        hashtags_input = self.cleaned_data.get('hashtags_str', '')
        hashtag_list = [h for h in hashtags_input.replace(',', ' ').split() if h]
        new_hashtags = []
        for ht in hashtag_list:
            ht_obj, created = HashTag.objects.get_or_create(name=ht)
            new_hashtags.append(ht_obj)
        
        # 다대다 관계 설정
        product.hashtags.set(new_hashtags)
        
        if not commit:
            product.save()
            
        return product
    

django_project_to_drf/products/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from .forms import ProductForm
from .models import Product

# Create your views here.
def product_list_view(request):
    products = Product.objects.all()
    return render(request, 'products/product_list.html', {'products':products})


@login_required
def product_create_view(request):
    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES, user=request.user)
        if form.is_valid():
            form.save()
            return redirect('products:product_list')
    else:
        form = ProductForm()
        
    return render(request, 'products/product_form.html', {'form':form})

@login_required
def product_detail_view(request, pk):
    product = get_object_or_404(Product, pk=pk)
    product.views += 1
    product.save()
    return render(request, 'products/product_detail.html', {'product':product, 'user': request.user})

@login_required
def product_update_view(request, pk):
    product = get_object_or_404(Product, pk=pk)
    if product.user != request.user:
        return redirect('products:product_detail', pk=pk)
    
    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES, instance=product)
        if form.is_valid():
            form.save()
            return redirect('products:product_detail', pk=pk)
    else:
        form = ProductForm(instance=product, initial={'hashtags_str':' '.join(ht.name for ht in product.hashtags.all())})
    return render(request, 'products/product_form.html', {'form':form, 'product':product})

@login_required
def product_delete_view(request, pk):
    product = get_object_or_404(Product, pk=pk)
    if product.user != request.user:
        return redirect('products:product_detail', pk=pk)
    
    if request.method == 'POST':
        product.delete()
        return redirect('products:product_list')
    return render(request, 'products/product_detail.html', {'product':product})

@login_required
def product_like_view(request, pk):
    product = get_object_or_404(Product, pk=pk)
    if request.user in product.likes.all():
        product.likes.remove(request.user)
    else:
        product.likes.add(request.user)
    return redirect('products:product_detail', pk=pk)

django_project_to_drf/products/templates/products/product_detail.html
{% extends 'base.html' %}
{% block content %}
<h2>{{ product.title }}</h2>
<p>
    등록자: 
    <a href="{% url 'accounts:profile' product.user.username %}">
        {{ product.user.username }}
    </a>
    / 등록일: {{ product.created_at|date:"Y-m-d H:i" }}
</p>
<p>조회수: {{ product.views }} / 찜수: {{ product.like_count }}</p>
{% if product.image %}
<img src="{{ product.image.url }}" width="300">
{% endif %}
<p>{{ product.description }}</p>
<p>
해시태그:
{% for ht in product.hashtags.all %}
    #{{ ht.name }}
{% endfor %}
</p>

<form action="{% url 'products:product_like' product.pk %}" method="post">
    {% csrf_token %}
    {% if user in product.likes.all %}
        <button type="submit">찜 취소</button>
    {% else %}
        <button type="submit">찜하기</button>
    {% endif %}
</form>

{% if user == product.user %}
    <a href="{% url 'products:product_update' product.pk %}">수정</a>
    <form action="{% url 'products:product_delete' product.pk %}" method="post" style="display:inline;">
        {% csrf_token %}
        <button type='submit'>삭제</button>
    </form>
{% endif %}


<a href="{% url 'products:product_list' %}">목록으로</a>
{% endblock %}

django_project_to_drf/products/templates/products/product_form.html
{% extends 'base.html' %}
{% block content %}
<h2>상품 등록/수정</h2>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">저장</button>
</form>
{% endblock %}

django_project_to_drf/products/templates/products/product_list.html
{% extends 'base.html' %}
{% block content %}
<h2>상품 목록</h2>

<ul>
{% for product in products %}
    <li>
        <a href="{% url 'products:product_detail' product.pk %}">
            /{{ product.title }} - ({{ product.user.username }})
            [조회수: {{ product.views }}, 찜수: {{ product.like_count }}]
            {% for ht in product.hashtags.all %}
                #{{ ht.name }}
            {% endfor %}
        </a>
    </li>
{% empty %}
    <li>상품이 없습니다.</li>
{% endfor %}
</ul>

<a href="{% url 'products:product_create' %}">상품 등록</a>
{% endblock %}